### ISSUE TITLE
ImportError: cannot import name SimpleTranslationMixin

### ISSUE THREAD

**Issue by kartikdanidhariya** [bitlabstudio/bitmazk-contact-form#2]
hi i am using djago-1.7.4

i try to use your module i install module from

pip install -e git://github.com/bitmazk/bitmazk-contact-form#egg=contact_form

after i install
django-libs
simple-translation

now it's give error for 
" File "/home/keyur/classified_django/src/contact-form/contact_form/models.py", line 5, in <module>
    from django_libs.models_mixins import SimpleTranslationMixin
ImportError: cannot import name SimpleTranslationMixin
"

so how can i solve this 
please help!!!
thanks in advance

**Comment by Tyrdall** [comment]
@kartikdanidhariya You will have to install a very old version of django-libs to fix this, but I guess this will lead to other issues.

We'll have to update this app.

**Comment by kartikdanidhariya** [comment]
hi 
i change the version
of 
 pip install simple-translation==0.8.6
pip install django-libs==1.16

and i add block in my template 

 {% block contact_form %}
		{% endblock %}

but still not any contact form render in temlate

**Comment by Tyrdall** [comment]
Well, you'll have to debug this issue. I don't know your setup and so it's impossible to know what's up.
